default: true

# MD013/line-length Line length
MD013: false

# MD033/no-inline-html Inline HTML
MD033: false

# MD036/no-emphasis-as-heading Emphasis used instead of a heading
MD036: false

# MD046/code-block-style Code block style
MD046: false
