default: true

# MD013/line-length Line length
MD013: false

# MD027/no-multiple-space-blockquote
MD027: false

# MD029/ol-prefix Ordered list item prefix
MD029: false

# MD033/no-inline-html Inline HTML
MD033: false

# MD036/no-emphasis-as-heading Emphasis used instead of a heading
MD036: false

# MD046/code-block-style Code block style
MD046: false
