__title__ = 'Formatter'
__description__ = 'A Sublime Text plugin to beautify and minify source code'
__url__ = 'https://github.com/bitst0rm-pub/Formatter'
__version__ = '1.8.9'
__author__ = 'Duc Ng. (bitst0rm)'
__license__ = 'MIT'
__copyright__ = 'Copyright (c) 2019-present'
